name: C/C++ CI

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
env:
  isNightly: ${{ contains(github.ref, 'dev') }}
  isReleaseCandidate: ${{ contains(github.ref, 'tags') && contains(github.ref, '-rc') }}
  isFinalRelease: ${{ contains(github.ref, 'tags') && contains(github.ref, '-release') }}

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Add ARM architecture to APT
      run: sudo dpkg --add-architecture armhf

    - name: Setup APT repositories for ARM
      run: sudo mv sources.list /etc/apt/sources.list

    - name: Update APT repositories
      run: sudo apt-get update

    - name: Get uClibc toolchain
      uses: i3h/download-release-asset@v1
      with:
        owner: telmomarques
        repo: uClibc-toolchain
        tag: latest
        file: toolchain.tar
    
    - name: Install uClibc ARM cross compiler
      run: tar -xf toolchain.tar

    - name: Compile
      run: cd src/motor && make clean && make CROSSCC=../../output/host/bin/arm-buildroot-linux-uclibcgnueabihf-gcc
    
    # - name: Upload Build Artifacts
    #   uses: actions/upload-artifact@v1
    #   with:
    #     name: motord
    #     path: src/motor/dist/motord

    - name: Update dev tag
      if: env.isNightly == 'true'
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: src/motor/dist/motord
        commit: dev
        draft: true
        replacesArtifacts: true
        tag : dev
        token: ${{ secrets.GITHUB_TOKEN }}

    # - name: Release (pre-release)
    #   if: env.isReleaseCandidate == 'true'
    #   uses: ncipollo/release-action@v1
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     prerelease: true
    #     artifacts: src/motor/dist/motord
        
    - name: Update latest-rc tag
      if: env.isReleaseCandidate == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest-rc
        allowUpdates: true
        replacesArtifacts: true
        prerelease: true
        artifacts: src/motor/dist/motord

    # - name: Release (final)
    #   if: env.isFinalRelease == 'true'
    #   uses: ncipollo/release-action@v1
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     artifacts: src/motor/dist/
        
    - name: Update latest tag
      if: env.isFinalRelease == 'true'
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: latest
        allowUpdates: true
        replacesArtifacts: true
        artifacts: src/motor/dist/motord